services:
  # API
  api:
    container_name: api_animeapp
    image: ${DOCKER_USERNAME_ENV}/api_animeapp:latest
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      - seq
    volumes:
      - keys:/keys

  # Frontend
  frontend:
    container_name: frontend_animeapp
    image: ${DOCKER_USERNAME_ENV}/frontend_animeapp:latest
    restart: always
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: ${API_URL}
      NEXT_PUBLIC_HUB_URL: ${HUB_URL}
      NEXT_PUBLIC_CDN_URL: ${CDN_URL}

  postgres:
    restart: always

  redis:
    restart: always

  rabbitmq:
    restart: always
    ports:
      - "127.0.0.1:15672:15672"

  seq:
    restart: always
    ports:
      - "127.0.0.1:5341:80"

networks:
  default:
    name: aniflow-network
    external: true
