services:
  # API
  api:
    container_name: api_animeapp
    build:
      context: .
      dockerfile: AnimeApp.API/Dockerfile
    ports:
      - "5000:5000"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    env_file:
      - .env.development
    depends_on:
      - postgres
      - redis
      - minio
      - seq
    volumes:
      - keys:/keys

  # Frontend
  frontend:
    container_name: frontend_animeapp
    build:
      context: ./AnimeApp.Frontend/animeapp
      target: prod
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:5000/api

  postgres:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  minio:
    ports:
      - "9000:9000"
      - "9001:9001"

  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"

  seq:
    ports:
      - "5341:80"

networks:
  default:
    name: npm_default
    external: true