// <auto-generated />
using System;
using System.Collections.Generic;
using AnimeApp.Core.Enums;
using AnimeApp.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AnimeApp.DataAccess.Migrations
{
    [DbContext(typeof(AnimeAppDbContext))]
    [Migration("20260607194608_FixAnimeRelatedCascade")]
    partial class FixAnimeRelatedCascade
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AnimeApp.Core.Models.Anime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AiredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("AniListId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("Duration")
                        .HasColumnType("integer");

                    b.Property<int?>("Episodes")
                        .HasColumnType("integer");

                    b.Property<int?>("EpisodesAired")
                        .HasColumnType("integer");

                    b.Property<List<ExternalLink>>("ExternalLinks")
                        .HasColumnType("jsonb");

                    b.Property<int?>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("KodikId")
                        .HasColumnType("text");

                    b.Property<int?>("MalId")
                        .HasColumnType("integer");

                    b.Property<int?>("MoonId")
                        .HasColumnType("integer");

                    b.Property<string>("MoonSlug")
                        .HasColumnType("text");

                    b.Property<bool>("Nsfw")
                        .HasColumnType("boolean");

                    b.Property<string>("PosterFileName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReleasedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Score")
                        .HasPrecision(3, 1)
                        .HasColumnType("double precision");

                    b.PrimitiveCollection<List<string>>("ScreenshotsFileName")
                        .HasColumnType("text[]");

                    b.Property<int?>("Season")
                        .HasColumnType("integer");

                    b.Property<int?>("Source")
                        .HasColumnType("integer");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("StudiosId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalScores")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StudiosId");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("Animes", (string)null);
                });

            modelBuilder.Entity("AnimeApp.Core.Models.AnimeIdCatalog", b =>
                {
                    b.Property<int>("MoonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MoonId"));

                    b.Property<bool>("IsParsed")
                        .HasColumnType("boolean");

                    b.Property<string>("KodikId")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MalId")
                        .HasColumnType("integer");

                    b.HasKey("MoonId");

                    b.HasIndex("KodikId")
                        .IsUnique();

                    b.HasIndex("MalId")
                        .IsUnique();

                    b.ToTable("AnimeIdCatalog", (string)null);
                });

            modelBuilder.Entity("AnimeApp.Core.Models.AnimeOst", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimeId")
                        .HasColumnType("integer");

                    b.Property<string>("Author")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<string>("SpotifyUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId");

                    b.ToTable("AnimeOsts", (string)null);
                });

            modelBuilder.Entity("AnimeApp.Core.Models.AnimeRelated", b =>
                {
                    b.Property<int>("AnimeId")
                        .HasColumnType("integer");

                    b.Property<int>("RelatedAnimeId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("AnimeId", "RelatedAnimeId");

                    b.HasIndex("RelatedAnimeId");

                    b.ToTable("AnimeRelateds", (string)null);
                });

            modelBuilder.Entity("AnimeApp.Core.Models.AnimeVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimeId")
                        .HasColumnType("integer");

                    b.Property<int?>("AnimeOstId")
                        .HasColumnType("integer");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId");

                    b.HasIndex("AnimeOstId");

                    b.ToTable("AnimeVideos", (string)null);
                });

            modelBuilder.Entity("AnimeApp.Core.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameRu")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameUa")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Genres", (string)null);
                });

            modelBuilder.Entity("AnimeApp.Core.Models.Studio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("MalId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PosterFileName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Studios", (string)null);
                });

            modelBuilder.Entity("AnimeApp.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarFileName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("BannerFileName")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfRegistration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("AnimeApp.Core.Models.UserAnime", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("AnimeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean");

                    b.Property<int?>("MyList")
                        .HasColumnType("integer");

                    b.Property<short?>("Rating")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "AnimeId");

                    b.HasIndex("AnimeId");

                    b.HasIndex("IsFavorite");

                    b.HasIndex("MyList");

                    b.HasIndex("Rating");

                    b.ToTable("UserAnimes", (string)null);
                });

            modelBuilder.Entity("AnimeGenre", b =>
                {
                    b.Property<int>("AnimeId")
                        .HasColumnType("integer");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.HasKey("AnimeId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("AnimeGenres", (string)null);
                });

            modelBuilder.Entity("AnimeApp.Core.Models.Anime", b =>
                {
                    b.HasOne("AnimeApp.Core.Models.Studio", "Studio")
                        .WithMany("Animes")
                        .HasForeignKey("StudiosId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsMany("AnimeApp.Core.Models.AnimeTitle", "Titles", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("AnimeId")
                                .HasColumnType("integer");

                            b1.Property<int>("Language")
                                .HasColumnType("integer");

                            b1.Property<int>("Type")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.HasKey("Id");

                            b1.HasIndex("AnimeId");

                            b1.ToTable("AnimeTitles", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AnimeId");
                        });

                    b.Navigation("Studio");

                    b.Navigation("Titles");
                });

            modelBuilder.Entity("AnimeApp.Core.Models.AnimeOst", b =>
                {
                    b.HasOne("AnimeApp.Core.Models.Anime", "Anime")
                        .WithMany("Music")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");
                });

            modelBuilder.Entity("AnimeApp.Core.Models.AnimeRelated", b =>
                {
                    b.HasOne("AnimeApp.Core.Models.Anime", "Anime")
                        .WithMany("Relateds")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnimeApp.Core.Models.Anime", "RelatedAnime")
                        .WithMany()
                        .HasForeignKey("RelatedAnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");

                    b.Navigation("RelatedAnime");
                });

            modelBuilder.Entity("AnimeApp.Core.Models.AnimeVideo", b =>
                {
                    b.HasOne("AnimeApp.Core.Models.Anime", "Anime")
                        .WithMany("Promos")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnimeApp.Core.Models.AnimeOst", null)
                        .WithMany("Videos")
                        .HasForeignKey("AnimeOstId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Anime");
                });

            modelBuilder.Entity("AnimeApp.Core.Models.UserAnime", b =>
                {
                    b.HasOne("AnimeApp.Core.Models.Anime", null)
                        .WithMany("UserAnimes")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnimeApp.Core.Models.User", null)
                        .WithMany("UserAnimes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnimeGenre", b =>
                {
                    b.HasOne("AnimeApp.Core.Models.Anime", null)
                        .WithMany()
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnimeApp.Core.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnimeApp.Core.Models.Anime", b =>
                {
                    b.Navigation("Music");

                    b.Navigation("Promos");

                    b.Navigation("Relateds");

                    b.Navigation("UserAnimes");
                });

            modelBuilder.Entity("AnimeApp.Core.Models.AnimeOst", b =>
                {
                    b.Navigation("Videos");
                });

            modelBuilder.Entity("AnimeApp.Core.Models.Studio", b =>
                {
                    b.Navigation("Animes");
                });

            modelBuilder.Entity("AnimeApp.Core.Models.User", b =>
                {
                    b.Navigation("UserAnimes");
                });
#pragma warning restore 612, 618
        }
    }
}
